db:
  port: 5432
  sslmode: disable
  host:   localhost
  username: postgres
  dbname: postgres

http:
  port: 80
  MaxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  port: 50080

grpcFD:
  port: 58081
  host: localhost

grpcCS:
  port: 8091
  host: localhost

grpcAuth:
  port: 8090
  host: localhost

fileStorage:
  Endpoint: fra1.digitaloceanspaces.com
  Bucket: onlineshop

