db:
  port: 5432
  sslmode: disable
  host:   165.232.68.67
  username: postgres
  dbname: postgres

http:
  port: 80
  MaxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  port: 50080

grpcFD:
  port: 58081
  host: 165.232.68.67

grpcCS:
  port: 8091
  host: 159.223.1.135

grpcAuth:
  port: 8090
  host: 159.223.1.135

fileStorage:
  Endpoint: fra1.digitaloceanspaces.com
  Bucket: onlineshop

